Testing
michaelogala/shot pull request #4
Opened 2016-10-03 21:26 UTC by andela-mogala

TESTS
### WHAT DOES THIS PR DO?
This PR tests all the features that have been developed in this app. Making sure that all features behave according to design and requirements

2016-10-05 12:24 UTC, mradeybee requested changes

2016-10-05 12:24 UTC, andela-aadepoju commented on app/controllers/redirects_controller.rb
What is the use of this method?

2016-10-05 12:24 UTC, andela-aadepoju commented on app/models/link.rb
> +  # after_create :scrape_title
Remove dead code.

2016-10-05 12:24 UTC, andela-aadepoju commented on coverage/.last_run.json
> +    "covered_percent": 98.67
You dont need to commit this file and the whole coverage folder.

2016-10-05 12:24 UTC, andela-aadepoju commented on spec/rails_helper.rb
> +  @password = Faker::Internet.password(8)
You can split this into multiple methods and call all of them in here.

2016-10-06 13:17 UTC, merged

2016-10-07 09:03 UTC, andela-fadebayo commented on app/controllers/redirects_controller.rb
> +    link = Link.find_by(slug: params[:slug])
This can be moved to Link model using `scope`.